apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: webapp-yellow
  labels:
    app: apache-app
spec:
  selector:
    matchLabels:
      app: apache-app
  replicas: 2
  template:
    metadata:
      labels:
        app: apache-app
    spec:
      containers:
        - name: apache-app-eric
          image: ericbek/coffee-website-2:main
          ports:
            - containerPort: 8080
